class_name ChargeGearCatalog
extends RefCounted

# Five visible machines, each with its own small readable tree. Nodes use a
# three-column/four-row coordinate so mouse, touch, keyboard and gamepad share
# the same navigation model.
const GEARS := [
	{"id": "striker", "name_ja": "撃鉄アーム", "name_en": "STRIKER ARM", "tag_ja": "手動・臨界", "tag_en": "MANUAL · CRIT", "accent": "4deeea", "desc_ja": "一打、連打、臨界と手動指令を改造する", "desc_en": "Rebuild direct hits, combos, criticals and manual commands"},
	{"id": "dynamo", "name_ja": "発電心臓", "name_en": "DYNAMO HEART", "tag_ja": "CHARGE経済", "tag_en": "CHARGE ECONOMY", "accent": "55efc4", "desc_ja": "直接打撃を恒久的な発電指令へ進化させる", "desc_en": "Evolve direct hits into a permanent generation command"},
	{"id": "autogun", "name_ja": "自律砲座", "name_en": "AUTOGUN RIG", "tag_ja": "AUTO主砲", "tag_en": "AUTO WEAPON", "accent": "9b5de5", "desc_ja": "終盤の主火力となる自動砲を変異させる", "desc_en": "Mutate the always-on cannon into the late-game damage engine"},
	{"id": "drone", "name_ja": "群制格納庫", "name_en": "DRONE HIVE", "tag_ja": "標識・支援", "tag_en": "MARK · SUPPORT", "accent": "ffb703", "desc_ja": "子機を増やし、手動標識をAUTO火力へ接続する", "desc_en": "Add drones and connect manual marks to automatic fire"},
	{"id": "core", "name_ja": "機核架台", "name_en": "CORE FRAME", "tag_ja": "討伐核共鳴", "tag_en": "STOLEN CORE", "accent": "ff5c5c", "desc_ja": "倒した魔獣の核を個別に増幅する", "desc_en": "Amplify each stolen mechanical-beast core independently"},
]

const SKILLS := [
	# STRIKER ARM
	{"id":"impact_coil","gear":"striker","col":1,"row":0,"max_rank":10,"base_cost":10.0,"growth":1.48,"parent":"","parent_rank":0,"name_ja":"衝撃コイル","name_en":"IMPACT COIL","desc_ja":"クリック威力を毎LV 36%増幅","desc_en":"+36% click power per rank"},
	{"id":"combo_gear","gear":"striker","col":0,"row":1,"max_rank":5,"base_cost":24.0,"growth":1.58,"parent":"impact_coil","parent_rank":2,"name_ja":"連打ギア","name_en":"COMBO GEAR","desc_ja":"連打倍率と最大段数を拡張","desc_en":"Extend combo power and its stack cap"},
	{"id":"critical_math","gear":"striker","col":2,"row":1,"max_rank":5,"base_cost":30.0,"growth":1.60,"parent":"impact_coil","parent_rank":2,"name_ja":"臨界演算","name_en":"CRITICAL MATH","desc_ja":"臨界率+4%、臨界威力も上昇","desc_en":"+4% crit chance and rising crit power"},
	{"id":"armor_punch","gear":"striker","col":0,"row":2,"max_rank":3,"base_cost":82.0,"growth":1.76,"parent":"combo_gear","parent_rank":2,"name_ja":"装甲穿孔器","name_en":"ARMOR PUNCH","desc_ja":"周期的な手動打撃へ追加衝撃波","desc_en":"Add a shockwave to periodic manual hits"},
	{"id":"execution_protocol","gear":"striker","col":2,"row":2,"max_rank":3,"base_cost":92.0,"growth":1.78,"parent":"critical_math","parent_rank":2,"name_ja":"処刑プロトコル","name_en":"EXECUTION PROTOCOL","desc_ja":"HP35%未満への手動威力を増幅","desc_en":"Boost manual damage below 35% enemy HP"},
	{"id":"harvest_knuckle","gear":"striker","col":0,"row":3,"max_rank":1,"base_cost":620.0,"growth":1.0,"parent":"armor_punch","parent_rank":3,"name_ja":"動力刈取拳","name_en":"HARVEST KNUCKLE","desc_ja":"10打ごとに追加CHARGEを刈り取る","desc_en":"Harvest bonus CHARGE every ten manual hits"},
	{"id":"twin_trigger","gear":"striker","col":2,"row":3,"max_rank":1,"base_cost":680.0,"growth":1.0,"parent":"execution_protocol","parent_rank":3,"name_ja":"双発指令","name_en":"TWIN TRIGGER","desc_ja":"手動臨界でAUTO砲が即時追撃","desc_en":"Manual criticals command an instant AUTO volley"},

	# DYNAMO HEART
	{"id":"charge_generator","gear":"dynamo","col":1,"row":0,"max_rank":10,"base_cost":16.0,"growth":1.48,"parent":"","parent_rank":0,"name_ja":"高効率発電機","name_en":"CHARGE GENERATOR","desc_ja":"手動CHARGE獲得量を毎LV増幅","desc_en":"Increase manual CHARGE generation per rank"},
	{"id":"auto_induction","gear":"dynamo","col":0,"row":1,"max_rank":5,"base_cost":34.0,"growth":1.58,"parent":"charge_generator","parent_rank":2,"name_ja":"自動誘導発電","name_en":"AUTO INDUCTION","desc_ja":"AUTO命中のCHARGE生成を増幅","desc_en":"Increase CHARGE generated by AUTO hits"},
	{"id":"dividend_coil","gear":"dynamo","col":2,"row":1,"max_rank":5,"base_cost":38.0,"growth":1.60,"parent":"charge_generator","parent_rank":2,"name_ja":"配当コイル","name_en":"DIVIDEND COIL","desc_ja":"累計100 CHARGEごとに配当を得る","desc_en":"Pay a dividend every 100 lifetime CHARGE"},
	{"id":"compound_interest","gear":"dynamo","col":0,"row":2,"max_rank":3,"base_cost":105.0,"growth":1.76,"parent":"auto_induction","parent_rank":2,"name_ja":"複利磁場","name_en":"COMPOUND FIELD","desc_ja":"未使用CHARGEが発電倍率へ変わる","desc_en":"Unspent CHARGE increases future generation"},
	{"id":"purchase_optimizer","gear":"dynamo","col":2,"row":2,"max_rank":3,"base_cost":118.0,"growth":1.78,"parent":"dividend_coil","parent_rank":2,"name_ja":"設計最適化器","name_en":"DESIGN OPTIMIZER","desc_ja":"全ノードの購入費を毎LV 6%削減","desc_en":"Reduce every node cost by 6% per rank"},
	{"id":"zero_output_generator","gear":"dynamo","col":0,"row":3,"max_rank":1,"base_cost":760.0,"growth":1.0,"parent":"compound_interest","parent_rank":3,"name_ja":"零出力発電","name_en":"ZERO-OUTPUT DRIVE","desc_ja":"直接打撃を6倍発電のPURE COMMANDへ恒久進化","desc_en":"Permanently evolve direct hits into 6× PURE COMMAND"},
	{"id":"feedback_loop","gear":"dynamo","col":2,"row":3,"max_rank":1,"base_cost":820.0,"growth":1.0,"parent":"purchase_optimizer","parent_rank":3,"name_ja":"永久帰還路","name_en":"PERPETUAL LOOP","desc_ja":"能力購入費の15%を即時還流","desc_en":"Immediately refund 15% of every node purchase"},

	# AUTOGUN RIG
	{"id":"auto_cannon","gear":"autogun","col":1,"row":0,"max_rank":10,"base_cost":14.0,"growth":1.48,"parent":"","parent_rank":0,"name_ja":"オートキャノン","name_en":"AUTO CANNON","desc_ja":"AUTO一発の威力を毎LV 42%増幅","desc_en":"+42% AUTO shot power per rank"},
	{"id":"rapid_relay","gear":"autogun","col":0,"row":1,"max_rank":5,"base_cost":28.0,"growth":1.58,"parent":"auto_cannon","parent_rank":2,"name_ja":"高速リレー","name_en":"RAPID RELAY","desc_ja":"AUTO射撃間隔を短縮","desc_en":"Shorten the automatic fire interval"},
	{"id":"heavy_ordnance","gear":"autogun","col":2,"row":1,"max_rank":5,"base_cost":34.0,"growth":1.60,"parent":"auto_cannon","parent_rank":2,"name_ja":"重砲弾頭","name_en":"HEAVY ORDNANCE","desc_ja":"連射速度を保ったまま威力を増幅","desc_en":"Increase power without slowing fire rate"},
	{"id":"burst_loader","gear":"autogun","col":0,"row":2,"max_rank":3,"base_cost":96.0,"growth":1.76,"parent":"rapid_relay","parent_rank":2,"name_ja":"斉射装填機","name_en":"BURST LOADER","desc_ja":"一定AUTO命中ごとに3倍斉射","desc_en":"Fire a 3× burst after repeated AUTO hits"},
	{"id":"chain_rounds","gear":"autogun","col":2,"row":2,"max_rank":3,"base_cost":108.0,"growth":1.78,"parent":"heavy_ordnance","parent_rank":2,"name_ja":"連鎖弾頭","name_en":"CHAIN ROUNDS","desc_ja":"AUTO攻撃が確率で追撃へ連鎖","desc_en":"AUTO shots can echo into follow-up hits"},
	{"id":"gatling_protocol","gear":"autogun","col":0,"row":3,"max_rank":1,"base_cost":880.0,"growth":1.0,"parent":"burst_loader","parent_rank":3,"name_ja":"ガトリング変異","name_en":"GATLING MUTATION","desc_ja":"威力を抑え、射撃間隔を45%まで短縮。レール砲と共存可能","desc_en":"Trade power for rapid fire; compatible with the rail mutation"},
	{"id":"rail_protocol","gear":"autogun","col":2,"row":3,"max_rank":1,"base_cost":880.0,"growth":1.0,"parent":"chain_rounds","parent_rank":3,"name_ja":"レール砲変異","name_en":"RAIL MUTATION","desc_ja":"射撃を遅くし、一発を3.2倍へ変異。ガトリングと共存可能","desc_en":"Transform shots to 3.2× power; compatible with the gatling mutation"},

	# DRONE HIVE
	{"id":"drone_bay","gear":"drone","col":1,"row":0,"max_rank":10,"base_cost":20.0,"growth":1.48,"parent":"","parent_rank":0,"name_ja":"ドローンベイ","name_en":"DRONE BAY","desc_ja":"全ドローンのAUTO威力を増幅","desc_en":"Increase automatic damage from every drone"},
	{"id":"swarm_clockwork","gear":"drone","col":0,"row":1,"max_rank":5,"base_cost":42.0,"growth":1.58,"parent":"drone_bay","parent_rank":2,"name_ja":"群制時計","name_en":"SWARM CLOCKWORK","desc_ja":"2LVごとにドローンを1機追加","desc_en":"Add one drone every two ranks"},
	{"id":"target_painter","gear":"drone","col":2,"row":1,"max_rank":5,"base_cost":44.0,"growth":1.60,"parent":"drone_bay","parent_rank":2,"name_ja":"標識照準器","name_en":"TARGET PAINTER","desc_ja":"手動入力が次のAUTOを標識強化","desc_en":"Manual inputs mark the next AUTO shot"},
	{"id":"charge_drone","gear":"drone","col":0,"row":2,"max_rank":3,"base_cost":126.0,"growth":1.76,"parent":"swarm_clockwork","parent_rank":2,"name_ja":"発電子機","name_en":"CHARGE DRONE","desc_ja":"ドローンごとのCHARGE生成を増幅","desc_en":"Increase generation from each active drone"},
	{"id":"hunter_drone","gear":"drone","col":2,"row":2,"max_rank":3,"base_cost":132.0,"growth":1.78,"parent":"target_painter","parent_rank":2,"name_ja":"狩猟子機","name_en":"HUNTER DRONE","desc_ja":"HP半分以下の敵へAUTO威力上昇","desc_en":"Boost AUTO damage below half enemy HP"},
	{"id":"support_fabricator","gear":"drone","col":0,"row":3,"max_rank":1,"base_cost":940.0,"growth":1.0,"parent":"charge_drone","parent_rank":3,"name_ja":"支援工廠","name_en":"SUPPORT FABRICATOR","desc_ja":"20AUTO命中ごとにCHARGEを製造","desc_en":"Fabricate bonus CHARGE every twenty AUTO hits"},
	{"id":"hive_mind","gear":"drone","col":2,"row":3,"max_rank":1,"base_cost":980.0,"growth":1.0,"parent":"hunter_drone","parent_rank":3,"name_ja":"群体知性","name_en":"HIVE MIND","desc_ja":"機数が多いほど全ドローンが強化","desc_en":"Every additional drone strengthens the whole swarm"},

	# CORE FRAME — nodes become available as their physical cores are recovered.
	{"id":"core_resonance","gear":"core","col":1,"row":0,"max_rank":10,"base_cost":52.0,"growth":1.50,"parent":"","parent_rank":0,"name_ja":"共鳴架台","name_en":"CORE RESONANCE","desc_ja":"所有する全機械核の効果を増幅","desc_en":"Amplify every recovered mechanical core"},
	{"id":"impact_memory","gear":"core","col":0,"row":1,"max_rank":5,"base_cost":96.0,"growth":1.68,"parent":"core_resonance","parent_rank":2,"requires_core":"impact_guidance","name_ja":"衝撃記憶","name_en":"IMPACT MEMORY","desc_ja":"ギアモウ核の衝撃波を増幅","desc_en":"Amplify the GEARMAW core shockwave"},
	{"id":"storage_memory","gear":"core","col":1,"row":1,"max_rank":5,"base_cost":102.0,"growth":1.68,"parent":"core_resonance","parent_rank":2,"requires_core":"deep_storage","name_ja":"蓄電記憶","name_en":"STORAGE MEMORY","desc_ja":"ヴォルトバック核の配当を増幅","desc_en":"Amplify the VAULTBACK core dividend"},
	{"id":"furnace_memory","gear":"core","col":2,"row":1,"max_rank":5,"base_cost":108.0,"growth":1.68,"parent":"core_resonance","parent_rank":2,"requires_core":"redheat_conversion","name_ja":"炉心記憶","name_en":"FURNACE MEMORY","desc_ja":"パイア核のオーバードライブを延長","desc_en":"Extend PYRE core overdrive"},
	{"id":"relay_memory","gear":"core","col":0,"row":2,"max_rank":5,"base_cost":116.0,"growth":1.70,"parent":"core_resonance","parent_rank":3,"requires_core":"cascade_relay","name_ja":"継電記憶","name_en":"RELAY MEMORY","desc_ja":"ヒドラ核の追撃率と威力を増幅","desc_en":"Amplify HYDRA core echo chance and power"},
	{"id":"swarm_memory","gear":"core","col":1,"row":2,"max_rank":5,"base_cost":122.0,"growth":1.70,"parent":"core_resonance","parent_rank":3,"requires_core":"swarm_clock","name_ja":"群制記憶","name_en":"SWARM MEMORY","desc_ja":"群制核のドローンとAUTO臨界を増幅","desc_en":"Amplify SWARM core drones and AUTO criticals"},
	{"id":"phase_memory","gear":"core","col":2,"row":2,"max_rank":5,"base_cost":128.0,"growth":1.70,"parent":"core_resonance","parent_rank":3,"requires_core":"phase_computation","name_ja":"位相記憶","name_en":"PHASE MEMORY","desc_ja":"解析速度と確定臨界威力を増幅","desc_en":"Accelerate analysis and empowered guaranteed crits"},
	{"id":"boss_matrix","gear":"core","col":1,"row":3,"max_rank":5,"base_cost":360.0,"growth":1.78,"parent":"core_resonance","parent_rank":5,"requires_boss_core":true,"name_ja":"主獣演算盤","name_en":"BOSS MATRIX","desc_ja":"通常ボスから奪った核効果を増幅","desc_en":"Amplify effects stolen from normal bosses"},

	# TIER II — unlocked after the first normal boss.
	{"id":"servo_overdrive","gear":"striker","tier":2,"col":1,"row":0,"max_rank":5,"base_cost":1800.0,"growth":1.86,"parent":"","parent_rank":0,"name_ja":"撃鉄サーボ過給","name_en":"STRIKER SERVO","desc_ja":"クリック威力を毎LV 28%増幅","desc_en":"Multiply click power by 1.28 per rank"},
	{"id":"command_link","gear":"striker","tier":2,"col":0,"row":1,"max_rank":3,"base_cost":6200.0,"growth":2.05,"parent":"servo_overdrive","parent_rank":2,"name_ja":"指令連結機","name_en":"COMMAND LINK","desc_ja":"手動指令をAUTO主砲の恒久火力へ接続","desc_en":"Convert manual command mastery into AUTO power"},
	{"id":"kinetic_recovery","gear":"striker","tier":2,"col":2,"row":1,"max_rank":3,"base_cost":6800.0,"growth":2.05,"parent":"servo_overdrive","parent_rank":2,"name_ja":"運動回生拳","name_en":"KINETIC RECOVERY","desc_ja":"クリック時のCHARGE回収量を増幅","desc_en":"Recover more CHARGE from every manual command"},
	{"id":"command_capacitor","gear":"striker","tier":2,"col":0,"row":2,"max_rank":3,"base_cost":18000.0,"growth":2.12,"parent":"command_link","parent_rank":3,"name_ja":"指令蓄圧器","name_en":"COMMAND CAPACITOR","desc_ja":"PURE指令のAUTO過給上限と持続を拡張","desc_en":"Extend PURE command boost capacity and duration"},
	{"id":"salvage_impulse","gear":"striker","tier":2,"col":2,"row":2,"max_rank":3,"base_cost":20000.0,"growth":2.12,"parent":"kinetic_recovery","parent_rank":3,"name_ja":"回収衝動","name_en":"SALVAGE IMPULSE","desc_ja":"25指令ごとに追加CHARGEを回収","desc_en":"Recover bonus CHARGE every twenty-five commands"},

	{"id":"deep_capacitor","gear":"dynamo","tier":2,"col":1,"row":0,"max_rank":5,"base_cost":2100.0,"growth":1.86,"parent":"","parent_rank":0,"name_ja":"深層蓄電槽","name_en":"DEEP CAPACITOR","desc_ja":"全発電量を毎LV 35%増幅","desc_en":"Multiply all generation by 1.35 per rank"},
	{"id":"war_dividend","gear":"dynamo","tier":2,"col":0,"row":1,"max_rank":3,"base_cost":7000.0,"growth":2.05,"parent":"deep_capacitor","parent_rank":2,"name_ja":"戦闘配当器","name_en":"WAR DIVIDEND","desc_ja":"AUTO命中による発電を追加増幅","desc_en":"Increase CHARGE dividends from AUTO hits"},
	{"id":"cost_compressor","gear":"dynamo","tier":2,"col":2,"row":1,"max_rank":3,"base_cost":7600.0,"growth":2.05,"parent":"deep_capacitor","parent_rank":2,"name_ja":"費用圧縮炉","name_en":"COST COMPRESSOR","desc_ja":"全スキル費用を毎LV 5%圧縮","desc_en":"Reduce every skill cost by 5% per rank"},
	{"id":"reserve_transformer","gear":"dynamo","tier":2,"col":0,"row":2,"max_rank":3,"base_cost":22000.0,"growth":2.12,"parent":"war_dividend","parent_rank":3,"name_ja":"予備変圧器","name_en":"RESERVE TRANSFORMER","desc_ja":"未使用CHARGEがAUTO発電を追加増幅","desc_en":"Banked CHARGE further amplifies AUTO generation"},
	{"id":"reclamation_bus","gear":"dynamo","tier":2,"col":2,"row":2,"max_rank":3,"base_cost":24000.0,"growth":2.12,"parent":"cost_compressor","parent_rank":3,"name_ja":"再利用母線","name_en":"RECLAMATION BUS","desc_ja":"能力購入費の一部を追加還流","desc_en":"Return an additional share of every skill purchase"},

	{"id":"twin_barrel","gear":"autogun","tier":2,"col":1,"row":0,"max_rank":5,"base_cost":2300.0,"growth":1.86,"parent":"","parent_rank":0,"name_ja":"双連砲身","name_en":"TWIN BARREL","desc_ja":"AUTO威力を毎LV 32%増幅","desc_en":"Multiply AUTO power by 1.32 per rank"},
	{"id":"phase_tracker","gear":"autogun","tier":2,"col":0,"row":1,"max_rank":3,"base_cost":7600.0,"growth":2.05,"parent":"twin_barrel","parent_rank":2,"name_ja":"位相追尾器","name_en":"PHASE TRACKER","desc_ja":"AUTO臨界率と主獣への追尾威力を上昇","desc_en":"Raise AUTO critical rate and boss tracking power"},
	{"id":"storm_loader","gear":"autogun","tier":2,"col":2,"row":1,"max_rank":3,"base_cost":8200.0,"growth":2.05,"parent":"twin_barrel","parent_rank":2,"name_ja":"雷装填機","name_en":"STORM LOADER","desc_ja":"斉射間隔を短縮し、斉射威力を増幅","desc_en":"Trigger stronger burst volleys more often"},
	{"id":"adaptive_feed","gear":"autogun","tier":2,"col":0,"row":2,"max_rank":3,"base_cost":24000.0,"growth":2.12,"parent":"phase_tracker","parent_rank":3,"name_ja":"適応給弾器","name_en":"ADAPTIVE FEED","desc_ja":"AUTO臨界弾の威力を追加増幅","desc_en":"Increase the power of AUTO critical rounds"},
	{"id":"capacitor_rounds","gear":"autogun","tier":2,"col":2,"row":2,"max_rank":3,"base_cost":26000.0,"growth":2.12,"parent":"storm_loader","parent_rank":3,"name_ja":"蓄電斉射弾","name_en":"CAPACITOR ROUNDS","desc_ja":"斉射発動時にCHARGEを回収","desc_en":"Recover CHARGE whenever a burst volley fires"},

	{"id":"replication_foundry","gear":"drone","tier":2,"col":1,"row":0,"max_rank":5,"base_cost":2500.0,"growth":1.86,"parent":"","parent_rank":0,"name_ja":"子機複製工廠","name_en":"REPLICATION FOUNDRY","desc_ja":"毎LVドローンを1機追加","desc_en":"Fabricate one additional drone per rank"},
	{"id":"synchronized_swarm","gear":"drone","tier":2,"col":0,"row":1,"max_rank":3,"base_cost":8200.0,"growth":2.05,"parent":"replication_foundry","parent_rank":2,"name_ja":"群体同期回路","name_en":"SYNCHRONIZED SWARM","desc_ja":"機数に応じたAUTO相乗倍率を増幅","desc_en":"Increase the damage synergy of every active drone"},
	{"id":"harvester_drones","gear":"drone","tier":2,"col":2,"row":1,"max_rank":3,"base_cost":8800.0,"growth":2.05,"parent":"replication_foundry","parent_rank":2,"name_ja":"採集子機群","name_en":"HARVESTER DRONES","desc_ja":"ドローンごとのAUTO発電量を増幅","desc_en":"Increase AUTO generation per active drone"},
	{"id":"mark_memory","gear":"drone","tier":2,"col":0,"row":2,"max_rank":3,"base_cost":26000.0,"growth":2.12,"parent":"synchronized_swarm","parent_rank":3,"name_ja":"標識記憶器","name_en":"MARK MEMORY","desc_ja":"標識斉射後も一部の標識を保持","desc_en":"Retain part of a mark stack after a marked volley"},
	{"id":"escort_protocol","gear":"drone","tier":2,"col":2,"row":2,"max_rank":3,"base_cost":28000.0,"growth":2.12,"parent":"harvester_drones","parent_rank":3,"name_ja":"護衛指令規約","name_en":"ESCORT PROTOCOL","desc_ja":"一定数の手動指令ごとに子機が即時追撃","desc_en":"Drones answer repeated manual commands with a volley"},

	{"id":"dual_core_link","gear":"core","tier":2,"col":1,"row":0,"max_rank":5,"base_cost":2800.0,"growth":1.86,"parent":"","parent_rank":0,"name_ja":"二核連結架台","name_en":"DUAL-CORE LINK","desc_ja":"回収核の共鳴倍率を毎LV増幅","desc_en":"Increase the resonance of all recovered cores"},
	{"id":"boss_core_forge","gear":"core","tier":2,"col":0,"row":1,"max_rank":3,"base_cost":9000.0,"growth":2.05,"parent":"dual_core_link","parent_rank":2,"requires_boss_core":true,"name_ja":"主獣核鍛造炉","name_en":"BOSS-CORE FORGE","desc_ja":"所有する主獣核ごとに全出力を増幅","desc_en":"Increase all output for every recovered boss core"},
	{"id":"resonance_economy","gear":"core","tier":2,"col":2,"row":1,"max_rank":3,"base_cost":9600.0,"growth":2.05,"parent":"dual_core_link","parent_rank":2,"name_ja":"共鳴経済圏","name_en":"RESONANCE ECONOMY","desc_ja":"所有する機械核ごとに発電量を増幅","desc_en":"Increase generation for every recovered mechanical core"},
	{"id":"core_prism","gear":"core","tier":2,"col":0,"row":2,"max_rank":3,"base_cost":29000.0,"growth":2.12,"parent":"boss_core_forge","parent_rank":3,"requires_boss_core":true,"name_ja":"機核プリズム","name_en":"CORE PRISM","desc_ja":"主獣核が手動・AUTO臨界を補正","desc_en":"Boss cores refine manual and AUTO critical output"},
	{"id":"salvage_lattice","gear":"core","tier":2,"col":2,"row":2,"max_rank":3,"base_cost":31000.0,"growth":2.12,"parent":"resonance_economy","parent_rank":3,"name_ja":"回収格子網","name_en":"SALVAGE LATTICE","desc_ja":"回収核数に応じて全発電を追加増幅","desc_en":"Recovered cores further amplify all generation"},

	# TIER III — unlocked after all six beast cores are recovered.
	{"id":"abyss_breaker","gear":"striker","tier":3,"col":1,"row":0,"max_rank":5,"base_cost":42000.0,"growth":2.0,"parent":"","parent_rank":0,"name_ja":"深淵破砕機","name_en":"ABYSS BREAKER","desc_ja":"真ルートのクリック威力を毎LV 25%増幅","desc_en":"Multiply late-route click power by 1.25 per rank"},
	{"id":"omega_trigger","gear":"striker","tier":3,"col":0,"row":1,"max_rank":3,"base_cost":190000.0,"growth":2.2,"parent":"abyss_breaker","parent_rank":2,"name_ja":"終端撃鉄","name_en":"OMEGA TRIGGER","desc_ja":"手動臨界のAUTO追撃を大幅増幅","desc_en":"Greatly amplify AUTO volleys commanded by manual crits"},
	{"id":"worldsplitter","gear":"striker","tier":3,"col":2,"row":1,"max_rank":1,"base_cost":1800000.0,"growth":1.0,"parent":"abyss_breaker","parent_rank":5,"name_ja":"地核割り","name_en":"WORLDSPLITTER","desc_ja":"25打ごとに最大HP比例の破砕波","desc_en":"Every 25th hit deals a max-HP fracture wave"},
	{"id":"terminal_cadence","gear":"striker","tier":3,"col":0,"row":2,"max_rank":3,"base_cost":620000.0,"growth":2.25,"parent":"omega_trigger","parent_rank":3,"name_ja":"終端指令律","name_en":"TERMINAL CADENCE","desc_ja":"一定指令ごとにAUTO全軍を即時斉射","desc_en":"Repeated commands trigger an instant full AUTO volley"},
	{"id":"fracture_archive","gear":"striker","tier":3,"col":2,"row":2,"max_rank":3,"base_cost":2900000.0,"growth":2.25,"parent":"worldsplitter","parent_rank":1,"name_ja":"破砕記録庫","name_en":"FRACTURE ARCHIVE","desc_ja":"地核割りの最大HP比例威力を増幅","desc_en":"Increase WORLDSPLITTER max-HP fracture damage"},

	{"id":"event_bank","gear":"dynamo","tier":3,"col":1,"row":0,"max_rank":5,"base_cost":46000.0,"growth":2.0,"parent":"","parent_rank":0,"name_ja":"事象蓄積庫","name_en":"EVENT BANK","desc_ja":"未使用CHARGEを全出力倍率へ変換","desc_en":"Convert banked CHARGE into a global output multiplier"},
	{"id":"infinite_dynamo","gear":"dynamo","tier":3,"col":0,"row":1,"max_rank":3,"base_cost":210000.0,"growth":2.2,"parent":"event_bank","parent_rank":2,"name_ja":"無限発電心臓","name_en":"INFINITE DYNAMO","desc_ja":"全発電量を爆発的に増幅","desc_en":"Exponentially increase every source of generation"},
	{"id":"perpetual_engine","gear":"dynamo","tier":3,"col":2,"row":1,"max_rank":1,"base_cost":2000000.0,"growth":1.0,"parent":"event_bank","parent_rank":5,"name_ja":"永久機関","name_en":"PERPETUAL ENGINE","desc_ja":"能力購入費の追加25%を即時還流","desc_en":"Immediately refund an additional 25% of skill costs"},
	{"id":"overflow_bus","gear":"dynamo","tier":3,"col":0,"row":2,"max_rank":3,"base_cost":680000.0,"growth":2.25,"parent":"infinite_dynamo","parent_rank":3,"name_ja":"溢流母線","name_en":"OVERFLOW BUS","desc_ja":"PURE指令のAUTO過給効率を増幅","desc_en":"Increase AUTO boost efficiency from PURE commands"},
	{"id":"closed_economy","gear":"dynamo","tier":3,"col":2,"row":2,"max_rank":3,"base_cost":3200000.0,"growth":2.25,"parent":"perpetual_engine","parent_rank":1,"name_ja":"閉鎖循環経済","name_en":"CLOSED ECONOMY","desc_ja":"能力購入費の追加分を最終還流","desc_en":"Return a final additional share of skill purchases"},

	{"id":"singularity_cannon","gear":"autogun","tier":3,"col":1,"row":0,"max_rank":5,"base_cost":50000.0,"growth":2.0,"parent":"","parent_rank":0,"name_ja":"特異点砲","name_en":"SINGULARITY CANNON","desc_ja":"AUTO威力を毎LV 22%増幅","desc_en":"Multiply AUTO power by 1.22 per rank"},
	{"id":"chrono_relay","gear":"autogun","tier":3,"col":0,"row":1,"max_rank":3,"base_cost":230000.0,"growth":2.2,"parent":"singularity_cannon","parent_rank":2,"name_ja":"時空継電器","name_en":"CHRONO RELAY","desc_ja":"AUTO射撃間隔を毎LV 12%短縮","desc_en":"Shorten AUTO fire interval by 12% per rank"},
	{"id":"annihilation_round","gear":"autogun","tier":3,"col":2,"row":1,"max_rank":1,"base_cost":2200000.0,"growth":1.0,"parent":"singularity_cannon","parent_rank":5,"name_ja":"消滅弾頭","name_en":"ANNIHILATION ROUND","desc_ja":"AUTO臨界弾の威力を4倍へ変異","desc_en":"Transform AUTO critical shots into 4× annihilation rounds"},
	{"id":"phase_magazine","gear":"autogun","tier":3,"col":0,"row":2,"max_rank":3,"base_cost":740000.0,"growth":2.25,"parent":"chrono_relay","parent_rank":3,"name_ja":"位相弾倉","name_en":"PHASE MAGAZINE","desc_ja":"雷斉射の倍率をさらに増幅","desc_en":"Further increase storm burst volley power"},
	{"id":"echo_chamber","gear":"autogun","tier":3,"col":2,"row":2,"max_rank":3,"base_cost":3400000.0,"growth":2.25,"parent":"annihilation_round","parent_rank":1,"name_ja":"反響薬室","name_en":"ECHO CHAMBER","desc_ja":"連鎖弾の発生率と追撃威力を増幅","desc_en":"Increase chain-round chance and follow-up damage"},

	{"id":"legion_protocol","gear":"drone","tier":3,"col":1,"row":0,"max_rank":5,"base_cost":54000.0,"growth":2.0,"parent":"","parent_rank":0,"name_ja":"軍団制御規約","name_en":"LEGION PROTOCOL","desc_ja":"群体AUTO威力を毎LV 15%増幅","desc_en":"Multiply swarm AUTO power by 1.15 per rank"},
	{"id":"horizon_mark","gear":"drone","tier":3,"col":0,"row":1,"max_rank":3,"base_cost":250000.0,"growth":2.2,"parent":"legion_protocol","parent_rank":2,"name_ja":"地平線標識","name_en":"HORIZON MARK","desc_ja":"手動標識による次回AUTO倍率を増幅","desc_en":"Increase the next AUTO multiplier from manual marks"},
	{"id":"world_hive","gear":"drone","tier":3,"col":2,"row":1,"max_rank":1,"base_cost":2400000.0,"growth":1.0,"parent":"legion_protocol","parent_rank":5,"name_ja":"世界群体","name_en":"WORLD HIVE","desc_ja":"12AUTOごとに最大HP比例の群体斉射","desc_en":"Every twelve AUTO hits launches a max-HP swarm volley"},
	{"id":"formation_matrix","gear":"drone","tier":3,"col":0,"row":2,"max_rank":3,"base_cost":800000.0,"growth":2.25,"parent":"horizon_mark","parent_rank":3,"name_ja":"陣形演算盤","name_en":"FORMATION MATRIX","desc_ja":"保持標識数と最大標識数を拡張","desc_en":"Increase retained and maximum target marks"},
	{"id":"sovereign_marker","gear":"drone","tier":3,"col":2,"row":2,"max_rank":3,"base_cost":3600000.0,"growth":2.25,"parent":"world_hive","parent_rank":1,"name_ja":"主権標識器","name_en":"SOVEREIGN MARKER","desc_ja":"世界群体の発動間隔と割合威力を強化","desc_en":"Improve WORLD HIVE cadence and max-HP damage"},

	{"id":"six_core_crown","gear":"core","tier":3,"col":1,"row":0,"max_rank":5,"base_cost":58000.0,"growth":2.0,"parent":"","parent_rank":0,"name_ja":"六核王冠","name_en":"SIX-CORE CROWN","desc_ja":"六獣核とランクに応じて全出力を増幅","desc_en":"Multiply all output through the six recovered beast cores"},
	{"id":"singularity_decoder","gear":"core","tier":3,"col":0,"row":1,"max_rank":3,"base_cost":270000.0,"growth":2.2,"parent":"six_core_crown","parent_rank":2,"name_ja":"特異点解読器","name_en":"SINGULARITY DECODER","desc_ja":"真ボスへの威力と封印解析速度を増幅","desc_en":"Increase true-boss damage and resonance decoding speed"},
	{"id":"world_engine_key","gear":"core","tier":3,"col":2,"row":1,"max_rank":1,"base_cost":2600000.0,"growth":1.0,"parent":"six_core_crown","parent_rank":5,"name_ja":"地核機神鍵","name_en":"WORLD-ENGINE KEY","desc_ja":"真ボスへの全出力を最終増幅","desc_en":"Apply a final global multiplier against the true boss"},
	{"id":"core_convergence","gear":"core","tier":3,"col":0,"row":2,"max_rank":3,"base_cost":860000.0,"growth":2.25,"parent":"singularity_decoder","parent_rank":3,"name_ja":"機核収束器","name_en":"CORE CONVERGENCE","desc_ja":"六獣核の総合出力を追加収束","desc_en":"Further focus the combined output of all six cores"},
	{"id":"lawbreaker_bus","gear":"core","tier":3,"col":2,"row":2,"max_rank":3,"base_cost":3900000.0,"growth":2.25,"parent":"world_engine_key","parent_rank":1,"name_ja":"法則破断母線","name_en":"LAWBREAKER BUS","desc_ja":"強化ボスへの単発出力上限を緩和","desc_en":"Relax direct-hit limits against enhanced bosses"},
]

static func gear(id: String) -> Dictionary:
	for definition in GEARS:
		if str(definition.id) == id:
			return definition
	return {}

static func skill(id: String) -> Dictionary:
	for definition in SKILLS:
		if str(definition.id) == id:
			return definition
	return {}

static func skills_for_gear(gear_id: String) -> Array[Dictionary]:
	var result: Array[Dictionary] = []
	for definition in SKILLS:
		if str(definition.gear) == gear_id:
			result.append(definition)
	return result

static func skills_for_gear_tier(gear_id: String, tier: int) -> Array[Dictionary]:
	var result: Array[Dictionary] = []
	for definition in SKILLS:
		if str(definition.gear) == gear_id and int(definition.get("tier", 1)) == tier:
			result.append(definition)
	return result

static func max_ranks_for_gear(gear_id: String) -> int:
	var total := 0
	for definition in SKILLS:
		if str(definition.gear) == gear_id:
			total += int(definition.max_rank)
	return total

static func max_ranks_for_gear_tier(gear_id: String, tier: int) -> int:
	var total := 0
	for definition in SKILLS:
		if str(definition.gear) == gear_id and int(definition.get("tier", 1)) == tier:
			total += int(definition.max_rank)
	return total

static func total_max_ranks() -> int:
	var total := 0
	for definition in SKILLS:
		total += int(definition.max_rank)
	return total
