class_name ChargeGearCatalog
extends RefCounted

# Five visible machines, each with its own small readable tree. Nodes use a
# three-column/four-row coordinate so mouse, touch, keyboard and gamepad share
# the same navigation model.
const GEARS := [
	{"id": "striker", "name_ja": "撃鉄アーム", "name_en": "STRIKER ARM", "tag_ja": "手動・臨界", "tag_en": "MANUAL · CRIT", "accent": "4deeea", "desc_ja": "一打、連打、臨界と手動指令を改造する", "desc_en": "Rebuild direct hits, combos, criticals and manual commands"},
	{"id": "dynamo", "name_ja": "発電心臓", "name_en": "DYNAMO HEART", "tag_ja": "CHARGE経済", "tag_en": "CHARGE ECONOMY", "accent": "55efc4", "desc_ja": "攻撃よりも発電を選ぶ新しい手動モードを開く", "desc_en": "Unlock a manual command that sacrifices damage for generation"},
	{"id": "autogun", "name_ja": "自律砲座", "name_en": "AUTOGUN RIG", "tag_ja": "AUTO主砲", "tag_en": "AUTO WEAPON", "accent": "9b5de5", "desc_ja": "終盤の主火力となる自動砲を変異させる", "desc_en": "Mutate the always-on cannon into the late-game damage engine"},
	{"id": "drone", "name_ja": "群制格納庫", "name_en": "DRONE HIVE", "tag_ja": "標識・支援", "tag_en": "MARK · SUPPORT", "accent": "ffb703", "desc_ja": "子機を増やし、手動標識をAUTO火力へ接続する", "desc_en": "Add drones and connect manual marks to automatic fire"},
	{"id": "core", "name_ja": "機核架台", "name_en": "CORE FRAME", "tag_ja": "討伐核共鳴", "tag_en": "STOLEN CORE", "accent": "ff5c5c", "desc_ja": "倒した魔獣の核を個別に増幅する", "desc_en": "Amplify each stolen mechanical-beast core independently"},
]

const SKILLS := [
	# STRIKER ARM
	{"id":"impact_coil","gear":"striker","col":1,"row":0,"max_rank":10,"base_cost":10.0,"growth":1.48,"parent":"","parent_rank":0,"name_ja":"衝撃コイル","name_en":"IMPACT COIL","desc_ja":"クリック威力を毎LV 36%増幅","desc_en":"+36% click power per rank"},
	{"id":"combo_gear","gear":"striker","col":0,"row":1,"max_rank":5,"base_cost":24.0,"growth":1.58,"parent":"impact_coil","parent_rank":2,"name_ja":"連打ギア","name_en":"COMBO GEAR","desc_ja":"連打倍率と最大段数を拡張","desc_en":"Extend combo power and its stack cap"},
	{"id":"critical_math","gear":"striker","col":2,"row":1,"max_rank":5,"base_cost":30.0,"growth":1.60,"parent":"impact_coil","parent_rank":2,"name_ja":"臨界演算","name_en":"CRITICAL MATH","desc_ja":"臨界率+4%、臨界威力も上昇","desc_en":"+4% crit chance and rising crit power"},
	{"id":"armor_punch","gear":"striker","col":0,"row":2,"max_rank":3,"base_cost":82.0,"growth":1.76,"parent":"combo_gear","parent_rank":2,"name_ja":"装甲穿孔器","name_en":"ARMOR PUNCH","desc_ja":"周期的な手動打撃へ追加衝撃波","desc_en":"Add a shockwave to periodic manual hits"},
	{"id":"execution_protocol","gear":"striker","col":2,"row":2,"max_rank":3,"base_cost":92.0,"growth":1.78,"parent":"critical_math","parent_rank":2,"name_ja":"処刑プロトコル","name_en":"EXECUTION PROTOCOL","desc_ja":"HP35%未満への手動威力を増幅","desc_en":"Boost manual damage below 35% enemy HP"},
	{"id":"harvest_knuckle","gear":"striker","col":0,"row":3,"max_rank":1,"base_cost":620.0,"growth":1.0,"parent":"armor_punch","parent_rank":3,"name_ja":"動力刈取拳","name_en":"HARVEST KNUCKLE","desc_ja":"10打ごとに追加CHARGEを刈り取る","desc_en":"Harvest bonus CHARGE every ten manual hits"},
	{"id":"twin_trigger","gear":"striker","col":2,"row":3,"max_rank":1,"base_cost":680.0,"growth":1.0,"parent":"execution_protocol","parent_rank":3,"name_ja":"双発指令","name_en":"TWIN TRIGGER","desc_ja":"手動臨界でAUTO砲が即時追撃","desc_en":"Manual criticals command an instant AUTO volley"},

	# DYNAMO HEART
	{"id":"charge_generator","gear":"dynamo","col":1,"row":0,"max_rank":10,"base_cost":16.0,"growth":1.48,"parent":"","parent_rank":0,"name_ja":"高効率発電機","name_en":"CHARGE GENERATOR","desc_ja":"手動CHARGE獲得量を毎LV増幅","desc_en":"Increase manual CHARGE generation per rank"},
	{"id":"auto_induction","gear":"dynamo","col":0,"row":1,"max_rank":5,"base_cost":34.0,"growth":1.58,"parent":"charge_generator","parent_rank":2,"name_ja":"自動誘導発電","name_en":"AUTO INDUCTION","desc_ja":"AUTO命中のCHARGE生成を増幅","desc_en":"Increase CHARGE generated by AUTO hits"},
	{"id":"dividend_coil","gear":"dynamo","col":2,"row":1,"max_rank":5,"base_cost":38.0,"growth":1.60,"parent":"charge_generator","parent_rank":2,"name_ja":"配当コイル","name_en":"DIVIDEND COIL","desc_ja":"累計100 CHARGEごとに配当を得る","desc_en":"Pay a dividend every 100 lifetime CHARGE"},
	{"id":"compound_interest","gear":"dynamo","col":0,"row":2,"max_rank":3,"base_cost":105.0,"growth":1.76,"parent":"auto_induction","parent_rank":2,"name_ja":"複利磁場","name_en":"COMPOUND FIELD","desc_ja":"未使用CHARGEが発電倍率へ変わる","desc_en":"Unspent CHARGE increases future generation"},
	{"id":"purchase_optimizer","gear":"dynamo","col":2,"row":2,"max_rank":3,"base_cost":118.0,"growth":1.78,"parent":"dividend_coil","parent_rank":2,"name_ja":"設計最適化器","name_en":"DESIGN OPTIMIZER","desc_ja":"全ノードの購入費を毎LV 6%削減","desc_en":"Reduce every node cost by 6% per rank"},
	{"id":"zero_output_generator","gear":"dynamo","col":0,"row":3,"max_rank":1,"base_cost":760.0,"growth":1.0,"parent":"compound_interest","parent_rank":3,"name_ja":"零出力発電","name_en":"ZERO-OUTPUT DRIVE","desc_ja":"0ダメージ・6倍発電のPURE CHARGE解禁","desc_en":"Unlock PURE CHARGE: zero damage, 6× generation"},
	{"id":"feedback_loop","gear":"dynamo","col":2,"row":3,"max_rank":1,"base_cost":820.0,"growth":1.0,"parent":"purchase_optimizer","parent_rank":3,"name_ja":"永久帰還路","name_en":"PERPETUAL LOOP","desc_ja":"能力購入費の15%を即時還流","desc_en":"Immediately refund 15% of every node purchase"},

	# AUTOGUN RIG
	{"id":"auto_cannon","gear":"autogun","col":1,"row":0,"max_rank":10,"base_cost":14.0,"growth":1.48,"parent":"","parent_rank":0,"name_ja":"オートキャノン","name_en":"AUTO CANNON","desc_ja":"AUTO一発の威力を毎LV 42%増幅","desc_en":"+42% AUTO shot power per rank"},
	{"id":"rapid_relay","gear":"autogun","col":0,"row":1,"max_rank":5,"base_cost":28.0,"growth":1.58,"parent":"auto_cannon","parent_rank":2,"name_ja":"高速リレー","name_en":"RAPID RELAY","desc_ja":"AUTO射撃間隔を短縮","desc_en":"Shorten the automatic fire interval"},
	{"id":"heavy_ordnance","gear":"autogun","col":2,"row":1,"max_rank":5,"base_cost":34.0,"growth":1.60,"parent":"auto_cannon","parent_rank":2,"name_ja":"重砲弾頭","name_en":"HEAVY ORDNANCE","desc_ja":"連射速度を保ったまま威力を増幅","desc_en":"Increase power without slowing fire rate"},
	{"id":"burst_loader","gear":"autogun","col":0,"row":2,"max_rank":3,"base_cost":96.0,"growth":1.76,"parent":"rapid_relay","parent_rank":2,"name_ja":"斉射装填機","name_en":"BURST LOADER","desc_ja":"一定AUTO命中ごとに3倍斉射","desc_en":"Fire a 3× burst after repeated AUTO hits"},
	{"id":"chain_rounds","gear":"autogun","col":2,"row":2,"max_rank":3,"base_cost":108.0,"growth":1.78,"parent":"heavy_ordnance","parent_rank":2,"name_ja":"連鎖弾頭","name_en":"CHAIN ROUNDS","desc_ja":"AUTO攻撃が確率で追撃へ連鎖","desc_en":"AUTO shots can echo into follow-up hits"},
	{"id":"gatling_protocol","gear":"autogun","col":0,"row":3,"max_rank":1,"base_cost":880.0,"growth":1.0,"parent":"burst_loader","parent_rank":3,"exclusive":"rail_protocol","name_ja":"ガトリング変異","name_en":"GATLING MUTATION","desc_ja":"威力を抑え、射撃間隔を45%まで短縮","desc_en":"Trade shot power for a 55% shorter interval"},
	{"id":"rail_protocol","gear":"autogun","col":2,"row":3,"max_rank":1,"base_cost":880.0,"growth":1.0,"parent":"chain_rounds","parent_rank":3,"exclusive":"gatling_protocol","name_ja":"レール砲変異","name_en":"RAIL MUTATION","desc_ja":"射撃を遅くし、一発を3.2倍へ変異","desc_en":"Fire slower, transforming each shot to 3.2× power"},

	# DRONE HIVE
	{"id":"drone_bay","gear":"drone","col":1,"row":0,"max_rank":10,"base_cost":20.0,"growth":1.48,"parent":"","parent_rank":0,"name_ja":"ドローンベイ","name_en":"DRONE BAY","desc_ja":"全ドローンのAUTO威力を増幅","desc_en":"Increase automatic damage from every drone"},
	{"id":"swarm_clockwork","gear":"drone","col":0,"row":1,"max_rank":5,"base_cost":42.0,"growth":1.58,"parent":"drone_bay","parent_rank":2,"name_ja":"群制時計","name_en":"SWARM CLOCKWORK","desc_ja":"2LVごとにドローンを1機追加","desc_en":"Add one drone every two ranks"},
	{"id":"target_painter","gear":"drone","col":2,"row":1,"max_rank":5,"base_cost":44.0,"growth":1.60,"parent":"drone_bay","parent_rank":2,"name_ja":"標識照準器","name_en":"TARGET PAINTER","desc_ja":"手動入力が次のAUTOを標識強化","desc_en":"Manual inputs mark the next AUTO shot"},
	{"id":"charge_drone","gear":"drone","col":0,"row":2,"max_rank":3,"base_cost":126.0,"growth":1.76,"parent":"swarm_clockwork","parent_rank":2,"name_ja":"発電子機","name_en":"CHARGE DRONE","desc_ja":"ドローンごとのCHARGE生成を増幅","desc_en":"Increase generation from each active drone"},
	{"id":"hunter_drone","gear":"drone","col":2,"row":2,"max_rank":3,"base_cost":132.0,"growth":1.78,"parent":"target_painter","parent_rank":2,"name_ja":"狩猟子機","name_en":"HUNTER DRONE","desc_ja":"HP半分以下の敵へAUTO威力上昇","desc_en":"Boost AUTO damage below half enemy HP"},
	{"id":"support_fabricator","gear":"drone","col":0,"row":3,"max_rank":1,"base_cost":940.0,"growth":1.0,"parent":"charge_drone","parent_rank":3,"name_ja":"支援工廠","name_en":"SUPPORT FABRICATOR","desc_ja":"20AUTO命中ごとにCHARGEを製造","desc_en":"Fabricate bonus CHARGE every twenty AUTO hits"},
	{"id":"hive_mind","gear":"drone","col":2,"row":3,"max_rank":1,"base_cost":980.0,"growth":1.0,"parent":"hunter_drone","parent_rank":3,"name_ja":"群体知性","name_en":"HIVE MIND","desc_ja":"機数が多いほど全ドローンが強化","desc_en":"Every additional drone strengthens the whole swarm"},

	# CORE FRAME — nodes become available as their physical cores are recovered.
	{"id":"core_resonance","gear":"core","col":1,"row":0,"max_rank":10,"base_cost":52.0,"growth":1.50,"parent":"","parent_rank":0,"name_ja":"共鳴架台","name_en":"CORE RESONANCE","desc_ja":"所有する全機械核の効果を増幅","desc_en":"Amplify every recovered mechanical core"},
	{"id":"impact_memory","gear":"core","col":0,"row":1,"max_rank":5,"base_cost":96.0,"growth":1.68,"parent":"core_resonance","parent_rank":2,"requires_core":"impact_guidance","name_ja":"衝撃記憶","name_en":"IMPACT MEMORY","desc_ja":"ギアモウ核の衝撃波を増幅","desc_en":"Amplify the GEARMAW core shockwave"},
	{"id":"storage_memory","gear":"core","col":1,"row":1,"max_rank":5,"base_cost":102.0,"growth":1.68,"parent":"core_resonance","parent_rank":2,"requires_core":"deep_storage","name_ja":"蓄電記憶","name_en":"STORAGE MEMORY","desc_ja":"ヴォルトバック核の配当を増幅","desc_en":"Amplify the VAULTBACK core dividend"},
	{"id":"furnace_memory","gear":"core","col":2,"row":1,"max_rank":5,"base_cost":108.0,"growth":1.68,"parent":"core_resonance","parent_rank":2,"requires_core":"redheat_conversion","name_ja":"炉心記憶","name_en":"FURNACE MEMORY","desc_ja":"パイア核のオーバードライブを延長","desc_en":"Extend PYRE core overdrive"},
	{"id":"relay_memory","gear":"core","col":0,"row":2,"max_rank":5,"base_cost":116.0,"growth":1.70,"parent":"core_resonance","parent_rank":3,"requires_core":"cascade_relay","name_ja":"継電記憶","name_en":"RELAY MEMORY","desc_ja":"ヒドラ核の追撃率と威力を増幅","desc_en":"Amplify HYDRA core echo chance and power"},
	{"id":"swarm_memory","gear":"core","col":1,"row":2,"max_rank":5,"base_cost":122.0,"growth":1.70,"parent":"core_resonance","parent_rank":3,"requires_core":"swarm_clock","name_ja":"群制記憶","name_en":"SWARM MEMORY","desc_ja":"群制核のドローンとAUTO臨界を増幅","desc_en":"Amplify SWARM core drones and AUTO criticals"},
	{"id":"phase_memory","gear":"core","col":2,"row":2,"max_rank":5,"base_cost":128.0,"growth":1.70,"parent":"core_resonance","parent_rank":3,"requires_core":"phase_computation","name_ja":"位相記憶","name_en":"PHASE MEMORY","desc_ja":"解析速度と確定臨界威力を増幅","desc_en":"Accelerate analysis and empowered guaranteed crits"},
	{"id":"boss_matrix","gear":"core","col":1,"row":3,"max_rank":5,"base_cost":360.0,"growth":1.78,"parent":"core_resonance","parent_rank":5,"requires_boss_core":true,"name_ja":"主獣演算盤","name_en":"BOSS MATRIX","desc_ja":"通常ボスから奪った核効果を増幅","desc_en":"Amplify effects stolen from normal bosses"},
]

static func gear(id: String) -> Dictionary:
	for definition in GEARS:
		if str(definition.id) == id:
			return definition
	return {}

static func skill(id: String) -> Dictionary:
	for definition in SKILLS:
		if str(definition.id) == id:
			return definition
	return {}

static func skills_for_gear(gear_id: String) -> Array[Dictionary]:
	var result: Array[Dictionary] = []
	for definition in SKILLS:
		if str(definition.gear) == gear_id:
			result.append(definition)
	return result

static func max_ranks_for_gear(gear_id: String) -> int:
	var total := 0
	for definition in SKILLS:
		if str(definition.gear) == gear_id:
			total += int(definition.max_rank)
	return total

static func total_max_ranks() -> int:
	var total := 0
	for definition in SKILLS:
		total += int(definition.max_rank)
	return total
